<div class="space-y-6">
@if($modo === 'eventos')
    <div class="grid gap-5 xl:grid-cols-[420px_1fr]">
        <form wire:submit="guardarEvento" class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm dark:border-neutral-700 dark:bg-neutral-900">
            <h2 class="text-lg font-bold">{{ $eventoId ? 'Editar evento' : 'Nuevo evento o lote' }}</h2><p class="mb-4 text-sm text-neutral-500">Agrupa reconocimientos de una ceremonia, concurso o actividad.</p>
            <div class="space-y-3">
                <input wire:model="eventoNombre" placeholder="Nombre del evento *" class="w-full rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800">
                <div class="grid grid-cols-2 gap-3"><input wire:model="eventoCategoria" placeholder="Categoría" class="rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800"><input wire:model="eventoFecha" type="date" class="rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800"></div>
                <input wire:model="eventoLugar" placeholder="Lugar" class="w-full rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800">
                <div class="grid grid-cols-2 gap-3"><input wire:model="eventoNivel" placeholder="Nivel" class="rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800"><input wire:model="eventoCiclo" placeholder="Ciclo escolar" class="rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800"></div>
                <select wire:model="eventoTipo" class="w-full rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800"><option value="">Tipo predeterminado</option>@foreach($tipos as $t)<option value="{{ $t->id }}">{{ $t->nombre }}</option>@endforeach</select>
                <select wire:model="eventoImagen" class="w-full rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800"><option value="">Plantilla predeterminada</option>@foreach($plantillas as $p)<option value="{{ $p->id }}">{{ $p->nombre ?: $p->descripcion }}</option>@endforeach</select>
                <select wire:model="eventoEstado" class="w-full rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800"><option value="activo">Activo</option><option value="cerrado">Cerrado</option><option value="archivado">Archivado</option></select>
                <textarea wire:model="eventoObservaciones" rows="3" placeholder="Observaciones" class="w-full rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800"></textarea>
                @error('eventoNombre')<p class="text-xs text-red-600">{{ $message }}</p>@enderror
            </div>
            <div class="mt-4 flex justify-end gap-2"><button type="button" wire:click="resetEvento" class="rounded-xl border px-4 py-2 text-sm font-bold">Limpiar</button><button class="rounded-xl bg-[#006492] px-4 py-2 text-sm font-bold text-white">Guardar evento</button></div>
        </form>
        <section class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm dark:border-neutral-700 dark:bg-neutral-900">
            <h2 class="mb-4 text-lg font-bold">Eventos registrados</h2><div class="grid gap-3 md:grid-cols-2">@forelse($eventos as $e)<article class="rounded-xl border p-4"><div class="flex justify-between gap-3"><div><h3 class="font-bold">{{ $e->nombre }}</h3><p class="text-xs text-neutral-500">{{ $e->fecha?->format('d/m/Y') }} · {{ $e->lugar ?: 'Sin lugar' }}</p></div><span class="h-fit rounded-full bg-[#88AC2E]/15 px-2 py-1 text-xs font-bold text-[#5d781c]">{{ $e->reconocimientos_count }}</span></div><div class="mt-3 text-xs text-neutral-500">{{ $e->tipo?->nombre ?: 'Tipo personalizado' }} · {{ ucfirst($e->estado) }}</div><div class="mt-4 flex gap-2"><button wire:click="editarEvento({{ $e->id }})" class="rounded-lg bg-[#006492] px-3 py-1.5 text-xs font-bold text-white">Editar</button><button wire:click="eliminarEvento({{ $e->id }})" class="rounded-lg border px-3 py-1.5 text-xs font-bold">Archivar/eliminar</button></div></article>@empty<p class="col-span-2 py-10 text-center text-neutral-500">Sin eventos.</p>@endforelse</div>
        </section>
    </div>
@elseif($modo === 'plantillas')
    <div class="grid gap-5 xl:grid-cols-[1fr_420px]">
        <section class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm dark:border-neutral-700 dark:bg-neutral-900"><h2 class="mb-4 text-lg font-bold">Configuración por plantilla</h2><div class="grid gap-4 md:grid-cols-2">@foreach($plantillas as $p)<article class="overflow-hidden rounded-xl border"><img src="{{ asset('storage/imagenesReconocimientos/'.$p->imagen) }}" class="h-40 w-full object-cover"><div class="p-3"><div class="flex justify-between"><strong>{{ $p->nombre ?: ($p->descripcion ?: 'Plantilla '.$p->id) }}</strong><span class="text-xs">{{ $p->reconocimientos_count }} usos</span></div><button wire:click="editarPlantilla({{ $p->id }})" class="mt-3 rounded-lg bg-[#006492] px-3 py-1.5 text-xs font-bold text-white">Configurar posiciones</button></div></article>@endforeach</div></section>
        <form wire:submit="guardarPlantilla" class="h-fit rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm dark:border-neutral-700 dark:bg-neutral-900"><h2 class="text-lg font-bold">Diseñador de posiciones</h2><p class="mb-4 text-sm text-neutral-500">Selecciona una plantilla y ajusta la distribución usada por el PDF.</p>@if($plantillaId)<div class="space-y-3"><input wire:model="plantillaNombre" placeholder="Nombre" class="w-full rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800"><select wire:model="plantillaOrientacion" class="w-full rounded-xl border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800"><option value="horizontal">Carta horizontal</option><option value="vertical">Carta vertical</option></select><label class="flex gap-2"><input type="checkbox" wire:model="plantillaActiva"> Plantilla activa</label><div class="grid grid-cols-2 gap-3"><label class="text-xs">Nombre: posición<input wire:model="nombreTop" type="number" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"></label><label class="text-xs">Nombre: tamaño<input wire:model="nombreTamano" type="number" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"></label><label class="text-xs">Descripción: posición<input wire:model="descripcionTop" type="number" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"></label><label class="text-xs">Descripción: tamaño<input wire:model="descripcionTamano" type="number" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"></label><label class="text-xs">Fecha: posición<input wire:model="fechaTop" type="number" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"></label><label class="text-xs">Firmas: posición<input wire:model="firmasTop" type="number" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"></label></div><button class="w-full rounded-xl bg-[#88AC2E] px-4 py-2 font-bold text-white">Guardar configuración</button></div>@else<div class="rounded-xl bg-neutral-50 p-8 text-center text-sm text-neutral-500 dark:bg-neutral-800">Selecciona una plantilla.</div>@endif</form>
    </div>
@else
    <div x-data="{sub:'tipos'}" class="space-y-5">
        <div class="inline-flex rounded-xl border bg-white p-1 dark:bg-neutral-900"><button @click="sub='tipos'" :class="sub==='tipos'?'bg-[#006492] text-white':''" class="rounded-lg px-4 py-2 text-sm font-bold">Tipos</button><button @click="sub='firmantes'" :class="sub==='firmantes'?'bg-[#006492] text-white':''" class="rounded-lg px-4 py-2 text-sm font-bold">Firmantes</button><button @click="sub='permisos'" :class="sub==='permisos'?'bg-[#006492] text-white':''" class="rounded-lg px-4 py-2 text-sm font-bold">Permisos</button></div>
        <div x-show="sub==='tipos'" class="grid gap-5 xl:grid-cols-[420px_1fr]"><form wire:submit="guardarTipo" class="rounded-2xl border bg-white p-5 dark:bg-neutral-900"><h2 class="font-bold">{{ $tipoId?'Editar':'Nuevo' }} tipo</h2><div class="mt-4 space-y-3"><input wire:model="tipoNombre" placeholder="Nombre *" class="w-full rounded-xl border-neutral-300 dark:bg-neutral-800"><input wire:model="tipoTitulo" placeholder="Título opcional" class="w-full rounded-xl border-neutral-300 dark:bg-neutral-800"><textarea wire:model="tipoDescripcion" rows="5" placeholder="Texto reutilizable *" class="w-full rounded-xl border-neutral-300 dark:bg-neutral-800"></textarea><select wire:model="tipoDestinatario" class="w-full rounded-xl border-neutral-300 dark:bg-neutral-800"><option value="alumno">Alumno</option><option value="docente">Docente</option><option value="externo">Externo</option><option value="institucion">Institución</option></select><input wire:model="tipoNiveles" placeholder="Niveles separados por coma" class="w-full rounded-xl border-neutral-300 dark:bg-neutral-800"><select wire:model="tipoImagen" class="w-full rounded-xl border-neutral-300 dark:bg-neutral-800"><option value="">Sin plantilla predeterminada</option>@foreach($plantillas as $p)<option value="{{ $p->id }}">{{ $p->nombre ?: $p->descripcion }}</option>@endforeach</select><label class="flex gap-2"><input type="checkbox" wire:model="tipoUsaLugar"> Utiliza lugar obtenido</label><label class="flex gap-2"><input type="checkbox" wire:model="tipoActivo"> Activo</label></div><div class="mt-4 flex justify-end gap-2"><button type="button" wire:click="resetTipo" class="rounded-xl border px-4 py-2">Limpiar</button><button class="rounded-xl bg-[#006492] px-4 py-2 font-bold text-white">Guardar</button></div></form><section class="rounded-2xl border bg-white p-5 dark:bg-neutral-900"><div class="space-y-3">@foreach($tipos as $t)<article class="rounded-xl border p-4"><div class="flex justify-between"><div><strong>{{ $t->nombre }}</strong><p class="text-xs text-neutral-500">{{ $t->destinatario_tipo }} · {{ $t->activo?'Activo':'Inactivo' }}</p></div><div class="flex gap-2"><button wire:click="editarTipo({{ $t->id }})" class="rounded-lg bg-[#006492] px-3 py-1 text-xs text-white">Editar</button><button wire:click="eliminarTipo({{ $t->id }})" class="rounded-lg border px-3 py-1 text-xs">Eliminar</button></div></div><p class="mt-2 text-sm text-neutral-600">{{ \Illuminate\Support\Str::limit(strip_tags($t->descripcion),160) }}</p></article>@endforeach</div></section></div>
        <div x-show="sub==='firmantes'" class="grid gap-5 xl:grid-cols-[420px_1fr]"><form wire:submit="guardarDirectivo" class="rounded-2xl border bg-white p-5 dark:bg-neutral-900"><h2 class="font-bold">{{ $directivoId?'Editar':'Nuevo' }} firmante</h2><div class="mt-4 space-y-3"><div class="grid grid-cols-[90px_1fr] gap-2"><input wire:model="directivoTitulo" placeholder="Título" class="rounded-xl border-neutral-300 dark:bg-neutral-800"><input wire:model="directivoNombre" placeholder="Nombre completo" class="rounded-xl border-neutral-300 dark:bg-neutral-800"></div><input wire:model="directivoCargo" placeholder="Cargo" class="w-full rounded-xl border-neutral-300 dark:bg-neutral-800"><input wire:model="directivoNiveles" placeholder="Niveles separados por coma" class="w-full rounded-xl border-neutral-300 dark:bg-neutral-800"><div class="grid grid-cols-2 gap-2"><input wire:model="directivoVigenciaInicio" type="date" class="rounded-xl border-neutral-300 dark:bg-neutral-800"><input wire:model="directivoVigenciaFin" type="date" class="rounded-xl border-neutral-300 dark:bg-neutral-800"></div><input wire:model="directivoOrden" type="number" placeholder="Orden" class="w-full rounded-xl border-neutral-300 dark:bg-neutral-800"><label class="text-xs">Firma digital<input type="file" wire:model="firmaArchivo" accept="image/*" class="mt-1 w-full"></label><label class="text-xs">Sello<input type="file" wire:model="selloArchivo" accept="image/*" class="mt-1 w-full"></label><label class="flex gap-2"><input type="checkbox" wire:model="directivoActivo"> Activo</label></div><div class="mt-4 flex justify-end gap-2"><button type="button" wire:click="resetDirectivo" class="rounded-xl border px-4 py-2">Limpiar</button><button class="rounded-xl bg-[#88AC2E] px-4 py-2 font-bold text-white">Guardar</button></div></form><section class="rounded-2xl border bg-white p-5 dark:bg-neutral-900"><div class="space-y-3">@foreach($directivos as $d)<article class="flex items-center justify-between rounded-xl border p-4"><div><strong>{{ $d->nombre_completo }}</strong><p class="text-xs text-neutral-500">{{ $d->cargo }} · Orden {{ $d->orden }} · {{ $d->activo?'Activo':'Inactivo' }}</p></div><button wire:click="editarDirectivo({{ $d->id }})" class="rounded-lg bg-[#006492] px-3 py-1.5 text-xs font-bold text-white">Editar</button></article>@endforeach</div></section></div>
        <div x-show="sub==='permisos'" class="rounded-2xl border bg-white p-5 dark:bg-neutral-900"><h2 class="text-lg font-bold">Permisos del módulo</h2><p class="mb-4 text-sm text-neutral-500">Controla qué puede hacer cada usuario en reconocimientos.</p><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-neutral-50 dark:bg-neutral-800"><tr><th class="p-3 text-left">Usuario</th>@foreach(['ver','crear','editar','aprobar','descargar','cancelar','administrar'] as $p)<th class="p-3">{{ ucfirst($p) }}</th>@endforeach<th></th></tr></thead><tbody class="divide-y dark:divide-neutral-800">@foreach($usuarios as $u)<tr><td class="p-3"><strong>{{ $u->name }}</strong><div class="text-xs text-neutral-500">{{ $u->email }}</div></td>@foreach(['ver','crear','editar','aprobar','descargar','cancelar','administrar'] as $p)<td class="p-3 text-center"><input type="checkbox" wire:model="permisos.{{ $u->id }}.{{ $p }}" class="rounded text-[#006492]"></td>@endforeach<td class="p-3"><button wire:click="guardarPermisos({{ $u->id }})" class="rounded-lg bg-[#006492] px-3 py-1.5 text-xs font-bold text-white">Guardar</button></td></tr>@endforeach</tbody></table></div></div>
    </div>
@endif
</div>
