<div class="grid gap-5 xl:grid-cols-[1fr_360px]">
<form wire:submit="actualizarReconocimiento" class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm dark:border-neutral-700 dark:bg-neutral-900">
    <div class="mb-5 flex flex-wrap justify-between gap-3"><div><h2 class="text-xl font-black">Editar reconocimiento</h2><p class="text-sm text-neutral-500">Versión {{ $reconocimiento->version }} · Creado {{ $reconocimiento->created_at?->format('d/m/Y H:i') }}</p></div><a href="{{ route('reconocimiento',['tab'=>'reconocimientos']) }}" class="rounded-xl border px-4 py-2 text-sm font-bold">Volver</a></div>
    <div class="grid gap-4 md:grid-cols-3"><label class="text-sm font-semibold">Evento<select wire:model="reconocimiento_evento_id" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"><option value="">Sin evento</option>@foreach($eventos as $e)<option value="{{ $e->id }}">{{ $e->nombre }}</option>@endforeach</select></label><label class="text-sm font-semibold">Tipo<select wire:model.live="reconocimiento_tipo_id" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"><option value="">Personalizado</option>@foreach($tipos as $t)<option value="{{ $t->id }}">{{ $t->nombre }}</option>@endforeach</select></label><label class="text-sm font-semibold">Estado<select wire:model="estado" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800">@foreach(\App\Models\Reconocimiento::ESTADOS as $e)<option value="{{ $e }}">{{ ucfirst($e) }}</option>@endforeach</select></label></div>
    <div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm font-semibold">Destinatario<input wire:model="reconocimiento_a" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"></label><label class="text-sm font-semibold">Lugar obtenido<input wire:model="lugar_obtenido" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"></label></div>
    <label class="mt-4 block text-sm font-semibold">Descripción<textarea wire:model="descripcion" rows="6" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"></textarea></label>
    <label class="mt-4 block max-w-xs text-sm font-semibold">Fecha<input wire:model="fecha" type="date" class="mt-1 w-full rounded-xl border-neutral-300 dark:bg-neutral-800"></label>
    @if($estado==='entregado')<div class="mt-4 grid gap-3 md:grid-cols-3"><select wire:model="delivery_method" class="rounded-xl border-neutral-300 dark:bg-neutral-800"><option value="">Método de entrega</option><option value="impreso">Impreso</option><option value="correo">Correo</option><option value="whatsapp">WhatsApp</option><option value="digital">Digital</option><option value="ceremonia">Ceremonia</option></select><input wire:model="delivery_to" placeholder="Recibido por" class="rounded-xl border-neutral-300 dark:bg-neutral-800"><input wire:model="delivery_notes" placeholder="Observaciones" class="rounded-xl border-neutral-300 dark:bg-neutral-800"></div>@endif
    @if($estado==='cancelado')<label class="mt-4 block text-sm font-semibold text-red-700">Motivo de cancelación<textarea wire:model="cancel_reason" rows="3" class="mt-1 w-full rounded-xl border-red-300 dark:bg-neutral-800"></textarea></label>@endif
    <section class="mt-5"><h3 class="mb-2 font-bold">Firmantes</h3><div class="grid gap-2 md:grid-cols-2">@foreach($directivosLista as $d)<label class="flex gap-2 rounded-xl border p-3"><input type="checkbox" wire:model="directivos" value="{{ $d->id }}" class="rounded text-[#88AC2E]"><span><strong>{{ $d->nombre_completo }}</strong><small class="block text-neutral-500">{{ $d->cargo }}</small></span></label>@endforeach</div></section>
    <section class="mt-5"><h3 class="mb-2 font-bold">Plantilla</h3><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($reconocimientosImagenes as $p)<label class="overflow-hidden rounded-xl border-2 {{ (int)$reconocimiento_imagen_id===$p->id?'border-[#88AC2E]':'border-neutral-200' }}"><input type="radio" wire:model="reconocimiento_imagen_id" value="{{ $p->id }}" class="absolute m-2"><img src="{{ asset('storage/imagenesReconocimientos/'.$p->imagen) }}" class="h-28 w-full object-cover"><div class="p-2 text-xs font-bold">{{ $p->nombre ?: $p->descripcion }}</div></label>@endforeach</div></section>
    @if($errors->any())<div class="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700"><ul>@foreach($errors->all() as $error)<li>• {{ $error }}</li>@endforeach</ul></div>@endif
    <div class="mt-5 flex justify-end"><button class="rounded-xl bg-[#006492] px-5 py-2.5 font-bold text-white">Guardar cambios</button></div>
</form>
<aside class="space-y-5"><section class="rounded-2xl border bg-white p-4 dark:bg-neutral-900"><h3 class="font-bold">Enviar por correo</h3><p class="mb-3 text-xs text-neutral-500">Requiere que el correo SMTP esté configurado en el archivo .env.</p><div class="space-y-2"><input wire:model="delivery_to" type="email" placeholder="correo@ejemplo.com" class="w-full rounded-xl border-neutral-300 text-sm dark:bg-neutral-800"><input wire:model="correo_asunto" placeholder="Asunto" class="w-full rounded-xl border-neutral-300 text-sm dark:bg-neutral-800"><textarea wire:model="correo_mensaje" rows="3" class="w-full rounded-xl border-neutral-300 text-sm dark:bg-neutral-800"></textarea><button type="button" wire:click="enviarCorreo" wire:loading.attr="disabled" class="w-full rounded-xl bg-[#006492] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Enviar PDF por correo</button></div></section><section class="rounded-2xl border bg-white p-4 dark:bg-neutral-900"><h3 class="font-bold">Historial</h3><div class="mt-3 max-h-[600px] space-y-3 overflow-auto">@forelse($historial as $h)<article class="border-l-2 border-[#006492] pl-3"><strong class="text-sm">{{ str_replace('_',' ',ucfirst($h->accion)) }}</strong><p class="text-xs text-neutral-500">{{ $h->descripcion }}</p><small class="text-[10px] text-neutral-400">{{ $h->created_at?->format('d/m/Y H:i') }} · {{ $h->usuario?->name ?: 'Sistema' }}</small></article>@empty<p class="text-sm text-neutral-500">Sin movimientos registrados.</p>@endforelse</div></section><a href="{{ route('reconocimiento.pdf',$reconocimiento) }}" target="_blank" class="block rounded-xl bg-[#88AC2E] px-4 py-3 text-center font-bold text-white">Abrir PDF</a></aside>
</div>
